/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.csl;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Rehman <12003065-317@umt.edu.pk>
 */
public class Demo extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDemo1 = new javax.swing.JButton();
        btnDemo2 = new javax.swing.JButton();
        btnDemo3 = new javax.swing.JButton();
        btnDemo4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("English to PSL");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(590, 610));
        setResizable(false);
        getContentPane().setLayout(null);

        btnDemo1.setBackground(new java.awt.Color(126, 42, 33));
        btnDemo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDemo1.setForeground(new java.awt.Color(255, 255, 255));
        btnDemo1.setText("Step By Step Translation Demo");
        btnDemo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDemo1);
        btnDemo1.setBounds(110, 310, 370, 40);

        btnDemo2.setBackground(new java.awt.Color(126, 42, 33));
        btnDemo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDemo2.setForeground(new java.awt.Color(255, 255, 255));
        btnDemo2.setText("Sentence Translation");
        btnDemo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemo2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDemo2);
        btnDemo2.setBounds(110, 360, 370, 40);

        btnDemo3.setBackground(new java.awt.Color(126, 42, 33));
        btnDemo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDemo3.setForeground(new java.awt.Color(255, 255, 255));
        btnDemo3.setText("Text File Translation");
        btnDemo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemo3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDemo3);
        btnDemo3.setBounds(110, 410, 370, 40);

        btnDemo4.setBackground(new java.awt.Color(126, 42, 33));
        btnDemo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDemo4.setForeground(new java.awt.Color(255, 255, 255));
        btnDemo4.setText("Translation + HamNoSys + Animation");
        btnDemo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemo4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDemo4);
        btnDemo4.setBounds(110, 460, 370, 40);

        jLabel1.setBackground(new java.awt.Color(237, 214, 136));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("English To PSL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 180, 300, 60);

        jLabel2.setBackground(new java.awt.Color(215, 194, 121));
        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MACHINE TRANSLATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 240, 340, 38);

        btnSettings.setBackground(new java.awt.Color(126, 42, 33));
        btnSettings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSettings.setText("Program Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSettings);
        btnSettings.setBounds(110, 510, 370, 40);

        lblBackGround.setBackground(new java.awt.Color(215, 194, 121));
        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signs1.png"))); // NOI18N
        getContentPane().add(lblBackGround);
        lblBackGround.setBounds(0, 0, 590, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemo1ActionPerformed
        new Demo1().setVisible(true);
    }//GEN-LAST:event_btnDemo1ActionPerformed

    private void btnDemo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemo2ActionPerformed
        new TranslateSentence().setVisible(true);
    }//GEN-LAST:event_btnDemo2ActionPerformed

    private void btnDemo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemo3ActionPerformed
        new TranslateFromFile().setVisible(true);
    }//GEN-LAST:event_btnDemo3ActionPerformed

    private void btnDemo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemo4ActionPerformed
        JFrame jf = SiGMLPlayer.mainFrame;
        jf.setVisible(true);
    }//GEN-LAST:event_btnDemo4ActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        Preferences.getPreferencesInstance().setVisible(true);
    }//GEN-LAST:event_btnSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemo1;
    private javax.swing.JButton btnDemo2;
    private javax.swing.JButton btnDemo3;
    private javax.swing.JButton btnDemo4;
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBackGround;
    // End of variables declaration//GEN-END:variables
}
