/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.csl;

import edu.stanford.nlp.trees.Tree;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.ScrollPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static org.csl.Nlp4.getDependencies;
import static utilhc.HNSUtils.indentXML;
import static utilhc.HNSUtils.sigmlFromHNSUItems;
import static utilhc.HNSUtils.symHNSItemsFromHNSUItems;



// This class is no longer used, it may be deleted
public class TextToSign extends javax.swing.JFrame {

    /**
     * Creates new form TextToSign
     */
    ScrollPane mainWindow;
    ArrayList<File> inputFiles = new ArrayList<File>();
    static ArrayList<String> sentences = new ArrayList();
    JFileChooser chooser;
    String chooserTitle = "Open Text File";
    static String filePath = "";
    static String fileName = "";
    public static boolean fileOpened = false;
    public TextToSign() {

        //super("");
        if(!Preferences.preferencesInitialized){
            Preferences.setUserPreferences();
        }
        if(MyUtils.verbs.size()==0){
            MyUtils.initializeVerbsHashtable();
            System.out.println("Verb entries ="+MyUtils.verbs.size());
        }
        if(MyUtils.rules.size()==0){
            MyUtils.readRulesFile();
            System.out.println(MyUtils.rules.size()+" rules found.");
        }
        initComponents();
        btnTranslateNext.setEnabled(false);
        setTablesProperties();
        initSwingComponents();
        initUtilComponents();
//        initBrowser();
//        mainWindow = new ScrollPane(ScrollPane.SCROLLBARS_AS_NEEDED);
//        mainWindow.add(jPanel1);
        //       initBrowserWithProxy("172.2.0.6");

        modelT2 = (DefaultTableModel) jTable2.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        warningL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaTranslatedSentence = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        DBShowBtn = new javax.swing.JButton();
        HNSBtn = new javax.swing.JButton();
        btnAnimate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaEnglishSentence = new javax.swing.JTextArea();
        lblEnglishSentence = new javax.swing.JLabel();
        btnTranslate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        sigmlTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnOpenFile = new javax.swing.JButton();
        btnTranslateNext = new javax.swing.JButton();
        lblFileName = new javax.swing.JLabel();
        txtSentenceNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chkAutoAnimation = new javax.swing.JCheckBox();

        setTitle("Hamnosys + Avatar Animation");

        jScrollPane5.setPreferredSize(new java.awt.Dimension(800, 715));

        jPanel1.setBackground(new java.awt.Color(182, 207, 164));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 715));

        warningL.setFont(new java.awt.Font("Raavi", 0, 12)); // NOI18N
        warningL.setForeground(new java.awt.Color(255, 51, 51));
        warningL.setText("[Building Corpus] Please Wait......");

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 255));

        txaTranslatedSentence.setColumns(4);
        txaTranslatedSentence.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txaTranslatedSentence.setLineWrap(true);
        txaTranslatedSentence.setRows(5);
        txaTranslatedSentence.setWrapStyleWord(true);
        txaTranslatedSentence.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(txaTranslatedSentence);

        jTable2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Gloss", "Manual (Symbols)", "Non-Manual", "Manual (Unicode)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setOpaque(false);
        jScrollPane4.setViewportView(jTable2);

        DBShowBtn.setBackground(new java.awt.Color(201, 201, 121));
        DBShowBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DBShowBtn.setText("Show All Signs in DB");
        DBShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBShowBtnActionPerformed(evt);
            }
        });

        HNSBtn.setBackground(new java.awt.Color(201, 201, 121));
        HNSBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        HNSBtn.setText("Generate HamNoSys");
        HNSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HNSBtnActionPerformed(evt);
            }
        });

        btnAnimate.setBackground(new java.awt.Color(201, 201, 121));
        btnAnimate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAnimate.setText("Animate");
        btnAnimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PSL Sentence: ");

        txaEnglishSentence.setColumns(20);
        txaEnglishSentence.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txaEnglishSentence.setRows(5);
        jScrollPane1.setViewportView(txaEnglishSentence);

        lblEnglishSentence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnglishSentence.setText("English Sentence: ");

        btnTranslate.setBackground(new java.awt.Color(201, 201, 121));
        btnTranslate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTranslate.setText("Translate Sentence");
        btnTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranslateActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        sigmlTA.setBackground(new java.awt.Color(204, 204, 204));
        sigmlTA.setColumns(4);
        sigmlTA.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        sigmlTA.setLineWrap(true);
        sigmlTA.setRows(5);
        sigmlTA.setWrapStyleWord(true);
        sigmlTA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(sigmlTA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Generated SigML Code:");

        btnOpenFile.setBackground(new java.awt.Color(201, 201, 121));
        btnOpenFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOpenFile.setText("Open File");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        btnTranslateNext.setBackground(new java.awt.Color(201, 201, 121));
        btnTranslateNext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTranslateNext.setText("Translate Next Sentence");
        btnTranslateNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranslateNextActionPerformed(evt);
            }
        });

        lblFileName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFileName.setForeground(new java.awt.Color(204, 0, 0));
        lblFileName.setText("No File Selected");

        txtSentenceNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sentence No:");

        chkAutoAnimation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkAutoAnimation.setText(" Automatically Play Animation");
        chkAutoAnimation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAutoAnimationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOpenFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSentenceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(warningL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HNSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnimate, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DBShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnglishSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTranslateNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(chkAutoAnimation)))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenFile)
                    .addComponent(lblFileName)
                    .addComponent(txtSentenceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblEnglishSentence))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkAutoAnimation)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTranslateNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HNSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnimate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DBShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningL)
                .addGap(32, 32, 32))
        );

        jScrollPane5.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HNSBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_HNSBtnActionPerformed
    {//GEN-HEADEREND:event_HNSBtnActionPerformed
        try {
            ArrayList<String> HNSList = new ArrayList<>();
            ArrayList<String> wordSiGMLList = new ArrayList<>();
            words.clear();
            boolean isEng, isNM = false;
            HamNoSys HNS;
            String manual = null, nmanual = null, wordSiGML = null;
            input = txaTranslatedSentence.getText();
            if (!input.equals("")) {
                isEng = (input.charAt(0) >= 'a' && input.charAt(0) <= 'z')
                        || (input.charAt(0) >= 'A' && input.charAt(0) <= 'Z');
                if (isEng) {
                    input = input.toLowerCase();
                }
            }
            removeAllRows(modelT2);
            input = input.replaceAll("[\\s\\_\\<۔*?>,.]", " ");
            StringTokenizer token;
            String word;
            String[] manualSiGML = null;
            int i = 0;
            token = new StringTokenizer(input, " ");
            while (token.hasMoreTokens()) {
                i++;
                word = token.nextToken();
                words.add(word);
                if (Hamnosys.containsKey(word)) {
                    HNS = Hamnosys.get(word);

//                    System.out.println(Hamnosys.containsKey(word));
                    manual = HNS.getmanualMarker().getCode();
                    nmanual = HNS.getnonmanualMarker().getCode();

//                HNSSymbol = Hamnosys.get(word);
                    String[] HNSSybmol
                            = {
                                manual
                            };

                    String[] HNSEnglish
                            = {
                                "Null"
                            };

                    if (manual != null) {
                        isEng = (manual.charAt(0) >= 'a' && manual.charAt(0) <= 'z')
                                || (manual.charAt(0) >= 'A' && manual.charAt(0) <= 'Z');
                        if (!isEng) {
                            HNSEnglish = symHNSItemsFromHNSUItems(HNSSybmol);
                            //toStdOut(HNSsymbol);
                            HNSList.add(manual + "\t" + word);
                        }
                    } else {
                        manual = "Null";
                    }
//                    System.out.println(word + "\t" + manual + "\t" + Arrays.toString(HNSString));
                    isNM = nmanual.length() != 0;
                    modelT2.addRow(new Object[]{
                        i, word, manual, isNM, Arrays.toString(HNSEnglish)
                    });

                    String[] ManualwithGloss
                            = {
                                manual + "\t" + word
                            };
                    manualSiGML = sigmlFromHNSUItems(ManualwithGloss);
                    wordSiGML = mergeSiGML(manualSiGML, nmanual);
                    wordSiGMLList.add(wordSiGML);
                } else {
                    modelT2.addRow(new Object[]{
                        i, word, "Null", false, "Null"
                    });
                }
            }

            if (wordSiGMLList.size() > 1) {
                outputSiGML = wordToSentenceSiGML(wordSiGMLList);
            } else {
                outputSiGML = wordSiGML;
            }
            if (outputSiGML != null) {
                String[] SiGML
                        = {
                            outputSiGML
                        };
                SiGML = indentXML(SiGML);
//            toStdOut(SiGML);
                outputSiGML = "";
                for (String lineOfCode : SiGML) {
                    outputSiGML += lineOfCode + "\n";
                }
                sigmlTA.setText(outputSiGML);
                sigmlTA.setCaretPosition(0);
                avatarReady = sigmlTA.getLineCount() > 4;
//            this.jScrollPane3.setVerticalScrollBar(null);
            } else {
                sigmlTA.setText("Gloss not Found in SignBank!");
                sigmlTA.setCaretPosition(0);
                avatarReady = sigmlTA.getLineCount() > 4;
            }
        } catch (Exception ex) {
            System.out.println(ex);
            Logger.getLogger(TextToSign.class.getName()).log(Level.SEVERE, null, ex);
            //            outputLOGS(ex);
        }
    }//GEN-LAST:event_HNSBtnActionPerformed
    public final String mergeSiGML(String[] manualSiGML, String nmanual) {
        String wordSiGML = "";
        byte flag = 0;
        for (String lineOfCode : manualSiGML) {
            if (flag == 2) {
                lineOfCode += nmanual;
            }
            wordSiGML += lineOfCode + "\n";
            flag++;
        }
        return wordSiGML;
    }

    public final String wordToSentenceSiGML(ArrayList<String> wordList) {
        String output = "", temp = "";
        for (int i = 0; i < wordList.size(); i++) {
            temp = wordList.get(i);
//            System.out.println(i + ": Before : \n" + temp);
            if (i == 0) {
                temp = temp.replaceFirst("</sigml>", "");
            } else if (i == wordList.size() - 1) {
                temp = temp.replace("<?xml version=\"1.0\" encoding=\"utf-8\"?>", "");
                temp = temp.replaceFirst("<sigml>", "");
            } else {
                temp = temp.replace("<?xml version=\"1.0\" encoding=\"utf-8\"?>", "");
                temp = temp.replaceFirst("<sigml>", "");
                temp = temp.replaceFirst("</sigml>", "");
            }
            output += temp;
//            System.out.println(i + ": After : \n" + temp);
        }
//        System.out.println(temp.contains("<?xml version=\"1.0\" encoding=\"utf-8\"?>"));
//        output = output.replace("\n\n", "");
//        ManualSiGML = indentXML(ManualSiGML);
//        return output.replace("\n\n", "");
        return output.replaceAll("\n+", "\n");
    }

    private void btnAnimateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAnimateActionPerformed
    {//GEN-HEADEREND:event_btnAnimateActionPerformed
//        System.out.println("Lines : " + sigmlTA.getLineCount());
        if (!txaTranslatedSentence.getText().equals(input)) {
            HNSBtnActionPerformed(null);
        }
        Socket socket = null;
        if (avatarReady) {
            try {

                socket = new Socket("127.0.0.1", 8052);
                if (socket.isConnected()) {
                    OutputStream outstream = socket.getOutputStream();
                    PrintWriter out = new PrintWriter(outstream);
                    out.print(outputSiGML);
                    out.close();
                    socket.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Please make sure the Signing Avatar is active!", "Info: " + "Operation Failed!", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
//                if (frame.isVisible())
                {
                    JOptionPane.showMessageDialog(null, "Please make sure the Signing Avatar is active!", "Info: " + "Operation Failed!", JOptionPane.INFORMATION_MESSAGE);
                    System.err.print(e);
                    /*
                    ProcessBuilder pb = new ProcessBuilder("C:\\Program Files\\Java\\jre1.8.0_73\\bin\\javaws.exe -localfile -offline -J-Djnlp.application.href=http://vhg.cmp.uea.ac.uk/tech/jas/vhg2015/jnlp/SiGMLPlayer.jnlp");
                    try {
                        pb.start();
                    } catch (IOException ex) {
                        Logger.getLogger(Preferences.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    */
                }
            }
        }
    }//GEN-LAST:event_btnAnimateActionPerformed

    private void DBShowBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DBShowBtnActionPerformed
    {//GEN-HEADEREND:event_DBShowBtnActionPerformed
//       Set<String> keys = ManualMapper.keySet();
        //Iterator<String> itr = pper.keySet().iterator();// Uncomment
        removeAllRows(modelT2);
        String key = "", gloss = "", manual = "", nmanual = "";
        Boolean isEng = false, isNM = false;
        int i = 0;
        Iterator<String> itr = Hamnosys.keySet().iterator();
        while (itr.hasNext()) {
            gloss = itr.next();
            manual = Hamnosys.get(gloss).getmanualMarker().getCode();
            nmanual = Hamnosys.get(gloss).getnonmanualMarker().getCode();

            String[] HNSSybmol
                    = {
                        manual
                    };

            String[] HNSEnglish
                    = {
                        "Null"
                    };

            if (manual != null) {
                isEng = (manual.charAt(0) >= 'a' && manual.charAt(0) <= 'z')
                        || (manual.charAt(0) >= 'A' && manual.charAt(0) <= 'Z');
                if (!isEng) {
                    HNSEnglish = symHNSItemsFromHNSUItems(HNSSybmol);
                }
            } else {
                manual = "Null";
            }

            isNM = nmanual.length() != 0;
            i++;
            modelT2.addRow(new Object[]{
                i, gloss, manual, isNM, Arrays.toString(HNSEnglish)
            });
        }


    }//GEN-LAST:event_DBShowBtnActionPerformed

    private void btnTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranslateActionPerformed
        // make all writes to the System.err stream silent (done to remove stanford log output)
        PrintStream err = System.err;
        System.setErr(new PrintStream(new OutputStream() {
            public void write(int b) {
            }
        }));

        String str="";
        if(fileOpened==false){
            str = txaEnglishSentence.getText();
        }else{
            int sentenceNo = Integer.parseInt(txtSentenceNo.getText());
            if(sentenceNo>0 && sentenceNo<=sentences.size()){
                str = sentences.get(sentenceNo);
                txaEnglishSentence.setText(str);
            }else{
                txaTranslatedSentence.setText("Sentence No "+sentenceNo+" not found.");
                return;
            }
        }
        Nlp4 parser = new Nlp4(); 
        Tree tree = parser.parse(str);
        String treeOutput=tree.toString();
        
        String str2 = str.replace("?", ""); // remove question mark if any (dependency tool correction)
        String dep= getDependencies(str2);
        
        MyTree tree3= MyUtils.constructAnnotatedTree(treeOutput,dep);
        MyList list = MyUtils.constructAnnotatedList(treeOutput, dep);
        String output = MyUtils.translate(str, tree3, list);
        txaTranslatedSentence.setText(output);
        // set error to normal again
        System.setErr(err);
        if(chkAutoAnimation.isSelected()){
            btnAnimateActionPerformed(null);
        }
    }//GEN-LAST:event_btnTranslateActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
       if(fileOpened==false){
            chooser = new JFileChooser();
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle(chooserTitle);
            chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

            if(chooser.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
                String name = chooser.getSelectedFile().getPath();
                if(name.contains(".txt")){
                    filePath = name;
                    fileName = chooser.getSelectedFile().getName();
                    readTextFile();
                    lblFileName.setText(fileName+" ("+sentences.size()+" sentences)");
                    lblFileName.setForeground(Color.BLUE);
                    fileOpened = true;
                    btnOpenFile.setText("Close File");
                    txtSentenceNo.setText("1");
                    btnTranslateNext.setEnabled(true);
                }
            }else{
                System.out.println("No selection.");
            }
        }else{
            btnOpenFile.setText("Open File");
            lblFileName.setText("No File Selected.");
            lblFileName.setForeground(new Color(204,51,0));
            sentences.clear();
            fileOpened = false;
            btnTranslateNext.setEnabled(false);
            txtSentenceNo.setText("");
        }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnTranslateNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranslateNextActionPerformed
        // make all writes to the System.err stream silent (done to remove stanford log output)
        PrintStream err = System.err;
        System.setErr(new PrintStream(new OutputStream() {
            public void write(int b) {
            }
        }));

        String str="";
        if(fileOpened==false){
            str = txaEnglishSentence.getText();
        }else{
            int sentenceNo = Integer.parseInt(txtSentenceNo.getText())+1;
            txtSentenceNo.setText(Integer.toString(sentenceNo));
            if(sentenceNo>0 && sentenceNo<=sentences.size()){
                str = sentences.get(sentenceNo);
                txaEnglishSentence.setText(str);
            }else{
                txaTranslatedSentence.setText("Sentence No "+sentenceNo+" not found.");
                return;
            }
        }
        Nlp4 parser = new Nlp4(); 
        Tree tree = parser.parse(str);
        String treeOutput=tree.toString();
        
        String str2 = str.replace("?", ""); // remove question mark if any (dependency tool correction)
        String dep= getDependencies(str2);
        
        MyTree tree3= MyUtils.constructAnnotatedTree(treeOutput,dep);
        MyList list = MyUtils.constructAnnotatedList(treeOutput, dep);
        String output = MyUtils.translate(str, tree3, list);
        txaTranslatedSentence.setText(output);
        // set error to normal again
        System.setErr(err); 
        if(chkAutoAnimation.isSelected()){
            btnAnimateActionPerformed(null);
        }
    }//GEN-LAST:event_btnTranslateNextActionPerformed

    private void chkAutoAnimationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAutoAnimationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAutoAnimationActionPerformed

    public static void readTextFile(){
        // this function translates a text file (line by line) and writes in output file
        //String path = "C:/Users/Rehman/Desktop/test3.txt";
        File file = new File(filePath);
        if(file.exists()){
            sentences.clear();
            try{
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String s="";
            String sentence = "";
            //int count = 0;
            while((s=br.readLine())!=null){
                //count++;
                //System.out.println("Translating Line no= "+count);
                for(int i=0; i<s.length(); i++){
                    sentence+=s.charAt(i);
                    if(sentence.equals(" ")){
                        sentence="";
                    }
                    if(s.charAt(i)=='.'||s.charAt(i)=='?'){
                        sentences.add(sentence);
                        sentence = "";
                    }
                }
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }else{
            System.out.println("Error: File "+filePath+" not found.");
        }   
    }
    private void setTablesProperties() {
        jTable2.setRowHeight(27);
//        jTable1.getCellRenderer(0, 0).getTableCellRendererComponent(jTable1, "", rootPaneCheckingEnabled, rootPaneCheckingEnabled, 1, 1).setBackground(new Color(39, 174, 96));
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            //      Table 2
            jTable2.getColumnModel().getColumn(0).setMinWidth(30);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(50);
            //      Table 2
            jTable2.getColumnModel().getColumn(1).setMinWidth(70);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(150);
            //      Table 2
            jTable2.getColumnModel().getColumn(3).setMinWidth(30);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(55);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(105);
        }
        setColumnFont("Manual (Symbols)");
        setColumnFont("Manual (Unicode)");
        setColumnFont("Gloss");
    }

    private void setColumnFont(String col) {
        if (col.equals("Manual (Symbols)")) {
            this.jTable2.getColumn(col).setCellRenderer(new DefaultTableCellRenderer() {
                        @Override
                        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
//                        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                            Font HNSFont = null;

                            try {
                                HNSFont = java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, new File("resources\\HamNoSys\\HamNoSysUnicode.ttf"));
                                HNSFont = HNSFont.deriveFont(Font.PLAIN, 20);

                            } catch (FontFormatException | IOException ex) {
                                Logger.getLogger(TextToSign.class
                                        .getName()).log(Level.SEVERE, null, ex);
                            }
                            try {

                                boolean isEng = (value.toString().charAt(0) >= 'a' && value.toString().charAt(0) <= 'z')
                                || (value.toString().charAt(0) >= 'A' && value.toString().charAt(0) <= 'Z');

                                setText(value.toString());

                                if (column == 2 && !isEng) {
                                    this.setFont(HNSFont);
                                } else {
                                    this.setFont(monoFont);
                                }
                            } catch (NullPointerException e) {
                                if (column == 2) {
                                    this.setFont(monoFont);
                                }
                                setText("NULL");
                            }
                            if (row % 2 == 0) {
                                this.setBackground(Color.WHITE);
                            } else {
                                this.setBackground(new Color(242, 242, 242));
                            }
                            return this;
                        }
                    }
            );
        } else if (col.equals("Manual (Unicode)")) {
            this.jTable2.getColumn(col).setCellRenderer(
                    new DefaultTableCellRenderer() {
                        @Override
                        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                            try {
                                //System.out.println("In it to win it!");
                                setText(value.toString());
                                if (column == 4) {
                                    this.setFont(monoFont.deriveFont(15));
                                }
                            } catch (NullPointerException e) {
                                setText("NULL");
                            }
                            if (row % 2 == 0) {
                                this.setBackground(Color.WHITE);
                            } else {
                                this.setBackground(new Color(242, 242, 242));
                            }
                            return this;
                        }
                    }
            );
        } else {
            this.jTable2.getColumn(col).setCellRenderer(
                    new DefaultTableCellRenderer() {
                        @Override
                        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                            try {
                                //System.out.println("In it to win it!");
                                setText(value.toString());
                                if (column == 1) {
                                    this.setFont(monoFont.deriveFont(15));
                                }
                            } catch (NullPointerException e) {
                                setText("NULL");
                            }
                            if (row % 2 == 0) {
                                this.setBackground(Color.WHITE);
                            } else {
                                this.setBackground(new Color(242, 242, 242));
                            }
                            return this;
                        }
                    }
            );
        }
    }

    private void removeAllRows(DefaultTableModel model) {
        while (model.getRowCount() != 0) {
            model.removeRow(0);
        }
    }

    public static void outputLOGS(Exception e) {
        FileWriter fw;
        PrintWriter pw;
        try {
            fw = new FileWriter("Log.txt", true);
            pw = new PrintWriter(fw);
            e.printStackTrace(pw);
            pw.close();
            fw.close();
            System.exit(1);

        } catch (IOException ex) {
            Logger.getLogger(TextToSign.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void loadSignDataBase() {
        HashMap<String, String> mMapper = new HashMap<>();
        String gloss, manual, nmanual;
        try {
            File folder = new File(Preferences.hamnosysDirectory);
//            File folder = new File(System.getProperty("user.dir"));
            File[] listOfFiles = folder.listFiles();
//            System.out.println(folder.getAbsolutePath());
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].getName().endsWith(".txt")) {
                    inputFiles.add(listOfFiles[i]);
                }
            }
            FileInputStream inputFile;
            InputStreamReader inputStreamReader;
            BufferedReader in;
            String line;
            for (int i = 0; i < inputFiles.size(); i++) //        int i=5;
            {
//                System.out.println(inputFiles.get(i).getAbsolutePath());
                inputFile = new FileInputStream(inputFiles.get(i));
//                inputStreamReader = new InputStreamReader(inputFile, "UTF-8");
                inputStreamReader = new InputStreamReader(inputFile);
                in = new BufferedReader(inputStreamReader);

                line = in.readLine();
                line = line.substring(1, line.length());
//                System.out.println("This is the text file line: " + line);
                while (line != null) {
                    StringTokenizer token;
                    token = new StringTokenizer(line, "\t");
//                    System.out.println("Token of line: " + token.countTokens());
                    if (token.countTokens() == 3) {
                        gloss = token.nextToken();
                        gloss = gloss.toLowerCase();
                        manual = token.nextToken();
                        nmanual = token.nextToken();
//                        if (!nmanual.equals("0000000000000,000000000,0000000000"))
//                            gloss = gloss + "*";
                        Hamnosys.put(gloss, new HamNoSys(new Manual(gloss, manual), new NonManual(gloss, nmanual)));
//                        System.out.println(gloss + " : " + manual + " , " + nmanual);
//                        mMapper.put(token.nextToken(), token.nextToken());
                    }
                    //                    System.out.println(token.nextToken() + "   " + token.nextToken() + " " + token.nextToken());
                    //                        System.out.println(token.nextToken());
                    line = in.readLine();

                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TextToSign.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TextToSign.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void initSwingComponents() {
        addressBar = new JTextField();
        addressBar.setSize(100, 50);
        addressBar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    URL = addressBar.getText();

                }

            }
        });
        frame = new JFrame("Browser");
        frame.add(addressBar, BorderLayout.NORTH);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                setVisible(true);
                frame.setVisible(false);
            }
        });
        frame.pack();
        frame.setSize(1300, 730);
        frame.setVisible(false);
        monoFont = this.getFont();
    }

    public final void initUtilComponents() {
        Hamnosys = new HashMap<>();
//        Thread readModel = new Thread() {
//            public void run()
//            {
        try {
            warningL.setText("Please Wait, Reading Model...");
            loadSignDataBase();
            warningL.setText("Ready!");
        } catch (Exception ex) {
            System.out.println(ex);
            Logger
                    .getLogger(TextToSign.class
                            .getName()).log(Level.SEVERE, null, ex);
        }
    }
//        };
//        readModel.start();
//    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextToSign.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextToSign.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextToSign.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextToSign.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TextToSign().setVisible(true);
//                TextToSign myFrame = new TextToSign();
//                myFrame.setVisible(true);
//                myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    //Utilities
    private static HashMap<String, String> tagset;
    private static HashMap<String, HamNoSys> Hamnosys;
    ArrayList<String> words = new ArrayList();
    //ArrayList<String> abbrivations = new ArrayList<>();
    private Font monoFont = null;
    private String outputSiGML = "", URL = "http://www.w3schools.com";
    private boolean avatarReady = false;
    private String input = "";
    //private String inputLine = "";

    // Swing Components
    private JFrame frame;
    private final DefaultTableModel modelT2;
    private JTextField addressBar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DBShowBtn;
    private javax.swing.JButton HNSBtn;
    private javax.swing.JButton btnAnimate;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnTranslate;
    private javax.swing.JButton btnTranslateNext;
    private javax.swing.JCheckBox chkAutoAnimation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblEnglishSentence;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JTextArea sigmlTA;
    private javax.swing.JTextArea txaEnglishSentence;
    private javax.swing.JTextArea txaTranslatedSentence;
    private javax.swing.JTextField txtSentenceNo;
    private javax.swing.JLabel warningL;
    // End of variables declaration//GEN-END:variables
}
